// This file is autogenerated when running rake app:run

import Appsignal from "@appsignal/javascript";

export default new Appsignal({
  key: "b032973f-732c-4c06-856a-3ec2eeb0b482",
  revision: "vue3-aaa",
  uri: "https://appsignal-endpoint.net/collect"
});
